# Generated by Django 2.2 on 2019-05-16 05:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], default='buy', max_length=4)),
                ('label', models.CharField(choices=[('R', 'red'), ('G', 'green')], max_length=1)),
                ('min_amount', models.FloatField()),
                ('max_amount', models.FloatField()),
                ('name_currency', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=datetime.date.today)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currencyads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
