# Generated by Django 2.1.7 on 2019-04-27 06:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], default='B', help_text='buy or sell', max_length=1)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('status',),
            },
        ),
        migrations.CreateModel(
            name='CurrencyAd',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('max_amount', models.IntegerField()),
                ('min_amount', models.IntegerField()),
                ('name_currency', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('publish_date', models.DateField(default=django.utils.timezone.now)),
                ('date', models.DateField(default=datetime.date.today)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currencyads', to='baiterx.Category')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currencyads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
