# Generated by Django 2.1.7 on 2019-04-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiterx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyad',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
