# Generated by Django 2.1.7 on 2019-04-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baiterx', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('status',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='type_of',
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(blank=True, choices=[('B', 'Buy'), ('S', 'Sell')], default='B', help_text='buy or sell', max_length=1),
        ),
    ]
